// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package bankrmi;

public final class AccountImpl_Stub
    extends java.rmi.server.RemoteStub
    implements bankrmi.Account, java.rmi.Remote
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("float balance()"),
	new java.rmi.server.Operation("void deposit(float)"),
	new java.rmi.server.Operation("void withdraw(float)")
    };
    
    private static final long interfaceHash = 3389451400590804060L;
    
    private static final long serialVersionUID = 2;
    
    private static boolean useNewInvoke;
    private static java.lang.reflect.Method $method_balance_0;
    private static java.lang.reflect.Method $method_deposit_1;
    private static java.lang.reflect.Method $method_withdraw_2;
    
    static {
	try {
	    java.rmi.server.RemoteRef.class.getMethod("invoke",
		new java.lang.Class[] {
		    java.rmi.Remote.class,
		    java.lang.reflect.Method.class,
		    java.lang.Object[].class,
		    long.class
		});
	    useNewInvoke = true;
	    $method_balance_0 = bankrmi.Account.class.getMethod("balance", new java.lang.Class[] {});
	    $method_deposit_1 = bankrmi.Account.class.getMethod("deposit", new java.lang.Class[] {float.class});
	    $method_withdraw_2 = bankrmi.Account.class.getMethod("withdraw", new java.lang.Class[] {float.class});
	} catch (java.lang.NoSuchMethodException e) {
	    useNewInvoke = false;
	}
    }
    
    // constructors
    public AccountImpl_Stub() {
	super();
    }
    public AccountImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of balance()
    public float balance()
	throws java.rmi.RemoteException
    {
	try {
	    if (useNewInvoke) {
		Object $result = ref.invoke(this, $method_balance_0, null, -6999057580273527148L);
		return ((java.lang.Float) $result).floatValue();
	    } else {
		java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);
		ref.invoke(call);
		float $result;
		try {
		    java.io.ObjectInput in = call.getInputStream();
		    $result = in.readFloat();
		} catch (java.io.IOException e) {
		    throw new java.rmi.UnmarshalException("error unmarshalling return", e);
		} finally {
		    ref.done(call);
		}
		return $result;
	    }
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deposit(float)
    public void deposit(float $param_float_1)
	throws bankrmi.Rejected, java.rmi.RemoteException
    {
	try {
	    if (useNewInvoke) {
		ref.invoke(this, $method_deposit_1, new java.lang.Object[] {new java.lang.Float($param_float_1)}, -4286485587922216374L);
	    } else {
		java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 1, interfaceHash);
		try {
		    java.io.ObjectOutput out = call.getOutputStream();
		    out.writeFloat($param_float_1);
		} catch (java.io.IOException e) {
		    throw new java.rmi.MarshalException("error marshalling arguments", e);
		}
		ref.invoke(call);
		ref.done(call);
	    }
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of withdraw(float)
    public void withdraw(float $param_float_1)
	throws bankrmi.Rejected, java.rmi.RemoteException
    {
	try {
	    if (useNewInvoke) {
		ref.invoke(this, $method_withdraw_2, new java.lang.Object[] {new java.lang.Float($param_float_1)}, 6542577535903995425L);
	    } else {
		java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 2, interfaceHash);
		try {
		    java.io.ObjectOutput out = call.getOutputStream();
		    out.writeFloat($param_float_1);
		} catch (java.io.IOException e) {
		    throw new java.rmi.MarshalException("error marshalling arguments", e);
		}
		ref.invoke(call);
		ref.done(call);
	    }
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
